name: Test PR React Typescript 2

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployments/react-ts-2
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: "🔧 setup node"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "📦 install dependencies"
        with:
          working-directory: deployments/react-ts-2
        uses: bahmutov/npm-install@v1

      - name: "🔍 run tests"
        run: npm run test --if-present
